name       : libuninameslist
version    : '20200313'
release    : 2
source     :
    - https://github.com/fontforge/libuninameslist/archive/20200313.tar.gz : 7689ed29e4dad3d1fbbfbe9aa43a45f494f2139bdee2e54a86620d664385130e
homepage   : https://github.com/fontforge/libuninameslist
license    : BSD-3-Clause
component  : programming.library
summary    : A library providing Unicode character names and annotations
description: |
    A library providing Unicode character names and annotations
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
