name       : libuninameslist
version    : '20200413'
release    : 3
source     :
    - https://github.com/fontforge/libuninameslist/archive/20200413.tar.gz : 6fc63e374b13bf9f7877cd7e50aacfdb017c9358e0036e150226540023eabce3
homepage   : https://github.com/fontforge/libuninameslist
license    : BSD-3-Clause
component  : programming.library
summary    : A library providing Unicode character names and annotations
description: |
    A library providing Unicode character names and annotations
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
